version: '3.8'
# Setup with three Docker containers to provide a PHP environment with MySQL and phpMyAdmin

services:
  mysql:
    image: mysql:latest
    container_name: mysql-wp-unique # Unique name for your MySQL container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: museum # Change this to a unique database name
      MYSQL_USER: Mohammadreza
      MYSQL_PASSWORD: root
    ports:
      - "3307:3307"  # Make sure this port doesn't conflict with other processes/containers
    volumes:
      - ./mysql_data:/var/lib/mysql # Ensure a unique volume path

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-wp-unique # Unique name for your PHP container
    ports:
      - "8082:80"  # Make sure this port doesn't conflict with other containers
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-wp-unique # Unique name for phpMyAdmin container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"  # Make sure this port doesn't conflict with other containers
    depends_on:
      - mysql
